### ISSUE TITLE
Cannot GET /error after run 

### ISSUE THREAD

**Issue by Yerli-Oyuncu** [SatoX69/Pastebin-Clone#1]
I clonned and installed depencies but im getting this error Cannot GET /

**Comment by SatoX69** [comment]
go to the "/save" endpoint and just for convenience, add a "/" endpoint that redirects you to the save endpoint, I'm too lazy to mod this

**Comment by Yerli-Oyuncu** [comment]
> go to the "/save" endpoint and just for convenience, add a "/" endpoint that redirects you to the save endpoint, I'm too lazy to mod this

idk too much about this things can you explain in more detail ?

**Comment by SatoX69** [comment]
I added a middleware for redirecting, it should work now. I'm archiving this repository
